import { prisma } from '@/lib/db/prisma';

/**
 * Builds a comprehensive GDPR-compliant data export for a member.
 * Includes all personal data stored across the platform.
 */
export async function buildMemberExport(userId: string) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    include: {
      profile: true,
      userRoles: { include: { role: true } },
      organization: {
        select: { id: true, name: true, slug: true },
      },
    },
  });

  if (!user) {
    throw new Error('User not found');
  }

  const [
    applications,
    jobApplications,
    courseEnrollments,
    courseProgress,
    memberProgramProgress,
    readinessChecklist,
    goals,
    learningProgress,
    resourceProgress,
    memberEvents,
    weeklyRecaps,
    pathwayStepProgress,
    trainingAccessRequests,
    programChangeRequests,
    benefitRequests,
    userCertifications,
    aiToolResults,
    messageThreads,
    placementRecord,
    placedOutcome,
    counselorAssignments,
    counselorNotes,
    partnerReferrals,
    memberSubgroups,
    mentorSessions,
    memberPoints,
    pointsTransactions,
    courseraCourseProgress,
    courseraBadgeProgress,
    courseraSkillsetProgress,
    preScreeningResponse,
    preScreeningDraft,
    placementSurveys,
    testimonials,
    nextBestActions,
    auditLogs,
    jobPostingApplications,
    aiJobMatches,
    applicationsAiFeedback,
    portalWorkflowEvents,
    emailSendLogs,
  ] = await Promise.all([
    prisma.application.findMany({ where: { userId } }),
    prisma.jobApplication.findMany({ where: { userId } }),
    prisma.courseEnrollment.findMany({ where: { userId } }),
    prisma.courseProgress.findMany({ where: { userId } }),
    prisma.memberProgramProgress.findMany({ where: { userId } }),
    prisma.readinessChecklist.findMany({ where: { userId } }),
    prisma.goal.findMany({ where: { userId } }),
    prisma.learningProgress.findMany({ where: { userId } }),
    prisma.resourceProgress.findMany({ where: { userId } }),
    prisma.memberEvent.findMany({ where: { userId } }),
    prisma.weeklyRecap.findMany({ where: { userId } }),
    prisma.pathwayStepProgress.findMany({ where: { userId } }),
    prisma.trainingAccessRequest.findMany({ where: { userId } }),
    prisma.programChangeRequest.findMany({ where: { userId } }),
    prisma.benefitRequest.findMany({ where: { userId } }),
    prisma.userCertification.findMany({ where: { userId } }),
    prisma.aIToolResult.findMany({ where: { userId } }),
    prisma.messageThread.findMany({
      where: { memberId: userId },
    }),
    prisma.placementRecord.findUnique({ where: { userId } }),
    prisma.placedOutcome.findUnique({ where: { userId } }),
    prisma.counselorAssignment.findMany({
      where: { memberId: userId },
      include: { counselor: { include: { user: { select: { fullName: true, email: true } } } } },
    }),
    prisma.counselorNote.findMany({
      where: { memberId: userId },
      include: { author: { select: { fullName: true, email: true } } },
    }),
    prisma.partnerReferral.findMany({
      where: { memberId: userId },
      include: { partner: { select: { name: true, slug: true } } },
    }),
    prisma.memberSubgroup.findMany({
      where: { memberId: userId },
      include: { subgroup: { select: { name: true, type: true } } },
    }),
    prisma.mentorSession.findMany({
      where: { memberId: userId },
      include: { mentor: { include: { user: { select: { fullName: true } } } } },
    }),
    prisma.memberPoints.findUnique({ where: { userId } }),
    prisma.pointsTransaction.findMany({ where: { userId } }),
    prisma.courseraCourseProgress.findMany({ where: { userId } }),
    prisma.courseraBadgeProgress.findMany({ where: { userId } }),
    prisma.courseraSkillsetProgress.findMany({ where: { userId } }),
    prisma.preScreeningResponse.findUnique({ where: { userId } }),
    prisma.preScreeningDraft.findUnique({ where: { userId } }),
    prisma.placementSurvey.findMany({ where: { userId } }),
    prisma.testimonial.findMany({ where: { memberId: userId } }),
    prisma.memberNextBestAction.findMany({ where: { memberId: userId } }),
    prisma.auditLog.findMany({ where: { actorUserId: userId } }),
    prisma.jobPostingApplication.findMany({ where: { studentId: userId } }),
    prisma.aIJobMatch.findMany({ where: { studentId: userId } }),
    prisma.applicationAiFeedback.findMany({ where: { userId } }),
    prisma.portalWorkflowEvent.findMany({ where: { actorUserId: userId } }),
    prisma.emailSendLog.findMany({ where: { userId }, orderBy: { createdAt: 'desc' } }),
  ]);

  const exportData = {
    exportMeta: {
      generatedAt: new Date().toISOString(),
      version: '1.0',
      purpose: 'GDPR data portability export',
    },
    member: {
      id: user.id,
      email: user.email,
      fullName: user.fullName,
      phone: user.phone,
      createdAt: user.createdAt?.toISOString() ?? null,
      updatedAt: user.updatedAt?.toISOString() ?? null,
      organization: user.organization,
      roles: user.userRoles.map((ur) => ur.role.name),

      // Assessment
      assessmentCompleted: user.assessmentCompleted,
      assessmentCompletedAt: user.assessmentCompletedAt?.toISOString() ?? null,
      assessmentScore: user.assessmentScore,
      assessmentScorePct: user.assessmentScorePct,
      assessmentAnswers: user.assessmentAnswers,
      programInterest: user.programInterest,
      careerRecommendationJson: user.careerRecommendationJson,

      // Enrollment
      enrolledProgram: user.enrolledProgram,
      enrolledAt: user.enrolledAt?.toISOString() ?? null,
      programChangedAt: user.programChangedAt?.toISOString() ?? null,
      coursesCompleted: user.coursesCompleted,
      courseraEnrollmentApproved: user.courseraEnrollmentApproved,
      courseraEnrollmentApprovedAt: user.courseraEnrollmentApprovedAt?.toISOString() ?? null,

      // Status / pipeline
      interviewEligible: user.interviewEligible,
      interviewRequestedAt: user.interviewRequestedAt?.toISOString() ?? null,
      interviewCompletedAt: user.interviewCompletedAt?.toISOString() ?? null,
      onboardingCompletedAt: user.onboardingCompletedAt?.toISOString() ?? null,
      tourCompletedAt: user.tourCompletedAt?.toISOString() ?? null,
      pipelineBoardStage: user.pipelineBoardStage,

      // WIOA
      wioaQualificationJson: user.wioaQualificationJson,
      wioaReviewStatus: user.wioaReviewStatus,
      wioaReviewedAt: user.wioaReviewedAt?.toISOString() ?? null,
      wioaReviewNotes: user.wioaReviewNotes,

      // Notifications
      notificationsUpdates: user.notificationsUpdates,
      notificationsReminders: user.notificationsReminders,

      // Last activity
      lastLoginAt: user.lastLoginAt?.toISOString() ?? null,
      staleTrainingDetectedAt: user.staleTrainingDetectedAt?.toISOString() ?? null,
      lastCourseraAutoSyncAt: user.lastCourseraAutoSyncAt?.toISOString() ?? null,
      deletedAt: user.deletedAt?.toISOString() ?? null,
    },
    profile: user.profile
      ? {
          address: user.profile.address,
          city: user.profile.city,
          state: user.profile.state,
          zip: user.profile.zip,
          profilePhone: user.profile.profilePhone,
          profileAddress: user.profile.profileAddress,
          profileLinkedin: user.profile.profileLinkedin,
          profileBio: user.profile.profileBio,
          dob: user.profile.dob?.toISOString() ?? null,
          veteranStatus: user.profile.veteranStatus,
          employmentStatus: user.profile.employmentStatus,
          educationLevel: user.profile.educationLevel,
          householdIncome: user.profile.householdIncome,
          referralSource: user.profile.referralSource,
          usCitizen: user.profile.usCitizen,
          authorizedToWork: user.profile.authorizedToWork,
          hasDisability: user.profile.hasDisability,
          ethnicity: user.profile.ethnicity,
          hasEmploymentBarrier: user.profile.hasEmploymentBarrier,
          barrierTypes: user.profile.barrierTypes,
          employmentStatusAtEnroll: user.profile.employmentStatusAtEnroll,
          financialAidInterest: user.profile.financialAidInterest,
          consentTerms: user.profile.consentTerms,
          consentCommunications: user.profile.consentCommunications,
          smsOptIn: user.profile.smsOptIn,
          role: user.profile.role,
          createdAt: user.profile.createdAt?.toISOString() ?? null,
          updatedAt: user.profile.updatedAt?.toISOString() ?? null,
          // Minor data
          isMinor: user.profile.isMinor,
          parentGuardianName: user.profile.parentGuardianName,
          parentGuardianEmail: user.profile.parentGuardianEmail,
          parentGuardianPhone: user.profile.parentGuardianPhone,
          parentalConsentGiven: user.profile.parentalConsentGiven,
          parentalConsentDate: user.profile.parentalConsentDate?.toISOString() ?? null,
          schoolName: user.profile.schoolName,
          schoolDistrict: user.profile.schoolDistrict,
          gradeLevel: user.profile.gradeLevel,
          studentId: user.profile.studentId,
          ferpaConsentGiven: user.profile.ferpaConsentGiven,
        }
      : null,
    applications: applications.map((a) => ({
      id: a.id,
      status: a.status,
      programInterest: a.programInterest,
      programRankedSlugs: a.programRankedSlugs,
      recommendedOnetCode: a.recommendedOnetCode,
      recommendedCareerTitle: a.recommendedCareerTitle,
      notes: a.notes,
      submittedAt: a.submittedAt?.toISOString() ?? null,
      referralSource: a.referralSource,
      createdAt: a.createdAt?.toISOString() ?? null,
      updatedAt: a.updatedAt?.toISOString() ?? null,
    })),
    jobApplications: jobApplications.map((ja) => ({
      id: ja.id,
      company: ja.company,
      role: ja.role,
      status: ja.status,
      appliedAt: ja.appliedAt?.toISOString() ?? null,
      source: ja.source,
      nextInterviewDate: ja.nextInterviewDate?.toISOString() ?? null,
      notes: ja.notes,
      url: ja.url,
      curatedJobId: ja.curatedJobId,
      createdAt: ja.createdAt?.toISOString() ?? null,
      updatedAt: ja.updatedAt?.toISOString() ?? null,
    })),
    courseEnrollments: courseEnrollments.map((ce) => ({
      id: ce.id,
      programSlug: ce.programSlug,
      isPrimary: ce.isPrimary,
      enrolledAt: ce.enrolledAt?.toISOString() ?? null,
      fundingSource: ce.fundingSource,
      fundingNotes: ce.fundingNotes,
      workspaceEmailProvisioned: ce.workspaceEmailProvisioned,
      workspaceEmail: ce.workspaceEmail,
      createdAt: ce.createdAt?.toISOString() ?? null,
      updatedAt: ce.updatedAt?.toISOString() ?? null,
    })),
    courseProgress: courseProgress.map((cp) => ({
      id: cp.id,
      programSlug: cp.programSlug,
      courseId: cp.courseId,
      courseSlug: cp.courseSlug,
      status: cp.status,
      percentComplete: cp.percentComplete,
      progressPct: cp.progressPct,
      scoreScaled: cp.scoreScaled,
      scoreRaw: cp.scoreRaw,
      startedAt: cp.startedAt?.toISOString() ?? null,
      completedAt: cp.completedAt?.toISOString() ?? null,
      lastActivityAt: cp.lastActivityAt?.toISOString() ?? null,
      createdAt: cp.createdAt?.toISOString() ?? null,
      lastUpdatedAt: cp.lastUpdatedAt?.toISOString() ?? null,
    })),
    memberProgramProgress: memberProgramProgress.map((mpp) => ({
      id: mpp.id,
      programSlug: mpp.programSlug,
      coursesCompleted: mpp.coursesCompleted,
      averagePercent: mpp.averagePercent,
      createdAt: mpp.createdAt?.toISOString() ?? null,
      lastUpdatedAt: mpp.lastUpdatedAt?.toISOString() ?? null,
    })),
    readinessChecklist: readinessChecklist.map((rc) => ({
      id: rc.id,
      section: rc.section,
      itemKey: rc.itemKey,
      completed: rc.completed,
      completedAt: rc.completedAt?.toISOString() ?? null,
      completedBy: rc.completedBy,
      notes: rc.notes,
      valueText: rc.valueText,
      createdAt: rc.createdAt?.toISOString() ?? null,
      updatedAt: rc.updatedAt?.toISOString() ?? null,
    })),
    goals: goals.map((g) => ({
      id: g.id,
      goalType: g.goalType,
      title: g.title,
      description: g.description,
      targetMetricType: g.targetMetricType,
      targetMetricValue: g.targetMetricValue,
      currentMetricValue: g.currentMetricValue,
      status: g.status,
      targetDate: g.targetDate?.toISOString() ?? null,
      completedAt: g.completedAt?.toISOString() ?? null,
      createdAt: g.createdAt?.toISOString() ?? null,
      updatedAt: g.updatedAt?.toISOString() ?? null,
    })),
    learningProgress: learningProgress.map((lp) => ({
      id: lp.id,
      pathwayId: lp.pathwayId,
      completed: lp.completed,
      progress: lp.progress,
      createdAt: lp.createdAt?.toISOString() ?? null,
      updatedAt: lp.updatedAt?.toISOString() ?? null,
    })),
    resourceProgress: resourceProgress.map((rp) => ({
      id: rp.id,
      resourceId: rp.resourceId,
      viewedAt: rp.viewedAt?.toISOString() ?? null,
      completedAt: rp.completedAt?.toISOString() ?? null,
      downloadedAt: rp.downloadedAt?.toISOString() ?? null,
      savedAt: rp.savedAt?.toISOString() ?? null,
      viewCount: rp.viewCount,
      completionStatus: rp.completionStatus,
      createdAt: rp.createdAt?.toISOString() ?? null,
      updatedAt: rp.updatedAt?.toISOString() ?? null,
    })),
    memberEvents: memberEvents.map((me) => ({
      id: me.id,
      eventName: me.eventName,
      entityType: me.entityType,
      entityId: me.entityId,
      metadata: me.metadata,
      sourcePage: me.sourcePage,
      sessionId: me.sessionId,
      createdAt: me.createdAt?.toISOString() ?? null,
    })),
    weeklyRecaps: weeklyRecaps.map((wr) => ({
      id: wr.id,
      weekStartDate: wr.weekStartDate?.toISOString() ?? null,
      weekEndDate: wr.weekEndDate?.toISOString() ?? null,
      recapJson: wr.recapJson,
      readinessScoreSnapshot: wr.readinessScoreSnapshot,
      goalsSnapshotJson: wr.goalsSnapshotJson,
      generatedAt: wr.generatedAt?.toISOString() ?? null,
      openedAt: wr.openedAt?.toISOString() ?? null,
      emailedAt: wr.emailedAt?.toISOString() ?? null,
      createdAt: wr.createdAt?.toISOString() ?? null,
    })),
    pathwayStepProgress: pathwayStepProgress.map((psp) => ({
      id: psp.id,
      pathwayId: psp.pathwayId,
      stepIndex: psp.stepIndex,
      stepTitle: psp.stepTitle,
      status: psp.status,
      completedAt: psp.completedAt?.toISOString() ?? null,
      notes: psp.notes,
      createdAt: psp.createdAt?.toISOString() ?? null,
      updatedAt: psp.updatedAt?.toISOString() ?? null,
    })),
    trainingAccessRequests: trainingAccessRequests.map((tar) => ({
      id: tar.id,
      providerKey: tar.providerKey,
      status: tar.status,
      requestedAt: tar.requestedAt?.toISOString() ?? null,
      approvedAt: tar.approvedAt?.toISOString() ?? null,
      activatedAt: tar.activatedAt?.toISOString() ?? null,
      rejectedAt: tar.rejectedAt?.toISOString() ?? null,
      notes: tar.notes,
      createdAt: tar.createdAt?.toISOString() ?? null,
      updatedAt: tar.updatedAt?.toISOString() ?? null,
    })),
    programChangeRequests: programChangeRequests.map((pcr) => ({
      id: pcr.id,
      currentProgramSlug: pcr.currentProgramSlug,
      requestedProgramSlug: pcr.requestedProgramSlug,
      reason: pcr.reason,
      status: pcr.status,
      adminNote: pcr.adminNote,
      reviewedAt: pcr.reviewedAt?.toISOString() ?? null,
      createdAt: pcr.createdAt?.toISOString() ?? null,
      updatedAt: pcr.updatedAt?.toISOString() ?? null,
    })),
    benefitRequests: benefitRequests.map((br) => ({
      id: br.id,
      benefit: br.benefit,
      status: br.status,
      createdAt: br.createdAt?.toISOString() ?? null,
      updatedAt: br.updatedAt?.toISOString() ?? null,
    })),
    certifications: userCertifications.map((uc) => ({
      id: uc.id,
      certName: uc.certName,
      earnedAt: uc.earnedAt?.toISOString() ?? null,
      createdAt: uc.createdAt?.toISOString() ?? null,
    })),
    aiToolResults: aiToolResults.map((aitr) => ({
      id: aitr.id,
      toolType: aitr.toolType,
      inputSummary: aitr.inputSummary,
      output: aitr.output,
      createdAt: aitr.createdAt?.toISOString() ?? null,
    })),
    messages: messageThreads.map((mt) => ({
      threadId: mt.id,
      kind: mt.kind,
      createdAt: mt.createdAt?.toISOString() ?? null,
      updatedAt: mt.updatedAt?.toISOString() ?? null,
    })),
    placementRecord: placementRecord
      ? {
          id: placementRecord.id,
          employerName: placementRecord.employerName,
          jobTitle: placementRecord.jobTitle,
          startDate: placementRecord.startDate?.toISOString() ?? null,
          salaryOffered: placementRecord.salaryOffered,
          placedAt: placementRecord.placedAt?.toISOString() ?? null,
          notes: placementRecord.notes,
          programSlug: placementRecord.programSlug,
          wageAtFollowUp: placementRecord.wageAtFollowUp,
          retentionStatus: placementRecord.retentionStatus,
          onboardingWindowEnd: placementRecord.onboardingWindowEnd?.toISOString() ?? null,
          retentionDecision: placementRecord.retentionDecision,
          startDateVerified: placementRecord.startDateVerified,
          fundingSource: placementRecord.fundingSource,
          grantReportingNotes: placementRecord.grantReportingNotes,
          createdAt: placementRecord.createdAt?.toISOString() ?? null,
          updatedAt: placementRecord.updatedAt?.toISOString() ?? null,
        }
      : null,
    placedOutcome: placedOutcome
      ? {
          id: placedOutcome.id,
          employerName: placedOutcome.employerName,
          jobTitle: placedOutcome.jobTitle,
          startingSalary: placedOutcome.startingSalary,
          placedAt: placedOutcome.placedAt?.toISOString() ?? null,
          createdAt: placedOutcome.createdAt?.toISOString() ?? null,
          updatedAt: placedOutcome.updatedAt?.toISOString() ?? null,
        }
      : null,
    counselorAssignments: counselorAssignments.map((ca) => ({
      id: ca.id,
      counselorName: ca.counselor.user.fullName,
      counselorEmail: ca.counselor.user.email,
      active: ca.active,
      assignedAt: ca.assignedAt?.toISOString() ?? null,
    })),
    counselorNotes: counselorNotes.map((cn) => ({
      id: cn.id,
      content: cn.content,
      authorName: cn.author?.fullName ?? 'Unknown',
      createdAt: cn.createdAt?.toISOString() ?? null,
      updatedAt: cn.updatedAt?.toISOString() ?? null,
    })),
    partnerReferrals: partnerReferrals.map((pr) => ({
      id: pr.id,
      partnerName: pr.partner.name,
      partnerSlug: pr.partner.slug,
      referredAt: pr.referredAt?.toISOString() ?? null,
    })),
    memberSubgroups: memberSubgroups.map((ms) => ({
      id: ms.id,
      subgroupName: ms.subgroup.name,
      subgroupType: ms.subgroup.type,
      assignedAt: ms.assignedAt?.toISOString() ?? null,
    })),
    mentorSessions: mentorSessions.map((ms) => ({
      id: ms.id,
      mentorName: ms.mentor.user.fullName,
      scheduledAt: ms.scheduledAt?.toISOString() ?? null,
      durationMin: ms.durationMin,
      status: ms.status,
      topic: ms.topic,
      notes: ms.notes,
      memberFeedback: ms.memberFeedback,
      hoursLogged: ms.hoursLogged,
      createdAt: ms.createdAt?.toISOString() ?? null,
    })),
    points: memberPoints
      ? {
          totalPoints: memberPoints.totalPoints,
          level: memberPoints.level,
          createdAt: memberPoints.createdAt?.toISOString() ?? null,
          updatedAt: memberPoints.updatedAt?.toISOString() ?? null,
        }
      : null,
    pointsTransactions: pointsTransactions.map((pt) => ({
      id: pt.id,
      event: pt.event,
      entityId: pt.entityId,
      points: pt.points,
      note: pt.note,
      createdAt: pt.createdAt?.toISOString() ?? null,
    })),
    courseraProgress: courseraCourseProgress.map((ccp) => ({
      id: ccp.id,
      courseName: ccp.courseName,
      courseraCourseId: ccp.courseraCourseId,
      programSlug: ccp.programSlug,
      enrollmentTime: ccp.enrollmentTime?.toISOString() ?? null,
      completionTime: ccp.completionTime?.toISOString() ?? null,
      overallProgress: ccp.overallProgress,
      learningHours: ccp.learningHours,
      isCompleted: ccp.isCompleted,
      courseGrade: ccp.courseGrade,
    })),
    courseraBadges: courseraBadgeProgress.map((cbp) => ({
      id: cbp.id,
      badgeTitle: cbp.badgeTitle,
      badgeCompleted: cbp.badgeCompleted,
      badgeCompletionTime: cbp.badgeCompletionTime?.toISOString() ?? null,
      lastSyncedAt: cbp.lastSyncedAt?.toISOString() ?? null,
    })),
    courseraSkillsets: courseraSkillsetProgress.map((csp) => ({
      id: csp.id,
      skillsetName: csp.skillsetName,
      progressPct: csp.progressPct,
      lastSyncedAt: csp.lastSyncedAt?.toISOString() ?? null,
    })),
    preScreeningResponse: preScreeningResponse
      ? {
          employmentStatus: preScreeningResponse.employmentStatus,
          primaryGoal: preScreeningResponse.primaryGoal,
          weeklyHours: preScreeningResponse.weeklyHours,
          barrier: preScreeningResponse.barrier,
          hearAbout: preScreeningResponse.hearAbout,
          hearAboutOther: preScreeningResponse.hearAboutOther,
          workforceAssistance: preScreeningResponse.workforceAssistance,
          createdAt: preScreeningResponse.createdAt?.toISOString() ?? null,
        }
      : null,
    preScreeningDraft: preScreeningDraft
      ? {
          employmentStatus: preScreeningDraft.employmentStatus,
          primaryGoal: preScreeningDraft.primaryGoal,
          weeklyHours: preScreeningDraft.weeklyHours,
          barrier: preScreeningDraft.barrier,
          hearAbout: preScreeningDraft.hearAbout,
          hearAboutOther: preScreeningDraft.hearAboutOther,
          workforceAssistance: preScreeningDraft.workforceAssistance,
          updatedAt: preScreeningDraft.updatedAt?.toISOString() ?? null,
        }
      : null,
    placementSurveys: placementSurveys.map((ps) => ({
      id: ps.id,
      wave: ps.wave,
      sentAt: ps.sentAt?.toISOString() ?? null,
      completedAt: ps.completedAt?.toISOString() ?? null,
      jobSatisfaction: ps.jobSatisfaction,
      trainingRelevance: ps.trainingRelevance,
      supportQuality: ps.supportQuality,
      whatHelpedMost: ps.whatHelpedMost,
      whatCouldImprove: ps.whatCouldImprove,
      stillEmployed: ps.stillEmployed,
      currentSalary: ps.currentSalary,
      allowTestimonial: ps.allowTestimonial,
    })),
    testimonials: testimonials.map((t) => ({
      id: t.id,
      content: t.content,
      rating: t.rating,
      programId: t.programId,
      placementId: t.placementId,
      source: t.source,
      status: t.status,
      consentGiven: t.consentGiven,
      createdAt: t.createdAt?.toISOString() ?? null,
      updatedAt: t.updatedAt?.toISOString() ?? null,
    })),
    nextBestActions: nextBestActions.map((nba) => ({
      id: nba.id,
      title: nba.title,
      description: nba.description,
      ctaLabel: nba.ctaLabel,
      ctaHref: nba.ctaHref,
      priority: nba.priority,
      status: nba.status,
      createdAt: nba.createdAt?.toISOString() ?? null,
      updatedAt: nba.updatedAt?.toISOString() ?? null,
    })),
    auditLogs: auditLogs.map((al) => ({
      id: al.id,
      action: al.action,
      targetType: al.targetType,
      targetId: al.targetId,
      metadata: al.metadata,
      createdAt: al.createdAt?.toISOString() ?? null,
    })),
    jobPostingApplications: jobPostingApplications.map((jpa) => ({
      id: jpa.id,
      jobId: jpa.jobId,
      status: jpa.status,
      appliedAt: jpa.appliedAt?.toISOString() ?? null,
    })),
    aiJobMatches: aiJobMatches.map((ajm) => ({
      id: ajm.id,
      jobId: ajm.jobId,
      matchScore: ajm.matchScore,
      matchReasons: ajm.matchReasons,
      createdAt: ajm.createdAt?.toISOString() ?? null,
    })),
    applicationAiFeedbacks: applicationsAiFeedback.map((aaf) => ({
      id: aaf.id,
      jobApplicationId: aaf.jobApplicationId,
      howUsed: aaf.howUsed,
      createdAt: aaf.createdAt?.toISOString() ?? null,
    })),
    portalWorkflowEvents: portalWorkflowEvents.map((pwe) => ({
      id: pwe.id,
      kind: pwe.kind,
      createdAt: pwe.createdAt?.toISOString() ?? null,
    })),
    // Emails the platform sent this member (email_send_logs) and what the
    // provider reported back. No raw recipient address is stored on the row.
    emailSendLogs: emailSendLogs.map((log) => ({
      id: log.id,
      templateKey: log.templateKey,
      subject: log.subject,
      status: log.status,
      attempts: log.attempts,
      skipReason: log.skipReason,
      failureReason: log.failureReason,
      lastEvent: log.lastEvent,
      lastEventAt: log.lastEventAt?.toISOString() ?? null,
      bounceType: log.bounceType,
      sentAt: log.sentAt?.toISOString() ?? null,
      createdAt: log.createdAt?.toISOString() ?? null,
    })),
  };

  return exportData;
}
