/**
 * Central registry of all WorkforceAP email/workflow cron jobs.
 * Single source of truth for schedule, description, audience, and API path.
 *
 * Each entry maps to a route under /api/cron/* and a schedule in vercel.json.
 */

export type CronDef = {
  id: string;
  name: string;
  description: string;
  schedule: string; // cron expression
  scheduleLabel: string; // human-readable
  apiPath: string; // relative, e.g. /api/cron/weekly-recap
  method: 'GET' | 'POST';
  icon: string; // material-symbols name
  category: 'member' | 'admin' | 'partner' | 'employer';
  audienceDescription: string; // who gets the email
  workflowKey: string; // matches WorkflowDiagnostic.workflow prefix for history lookup
};

export const CRON_REGISTRY: CronDef[] = [
  {
    id: 'weekly-recap',
    name: 'Weekly Recap Email',
    description: 'Sends a personalized weekly recap to enrolled members who have not received one this week.',
    schedule: '0 18 * * 0',
    scheduleLabel: 'Sunday 6PM UTC',
    apiPath: '/api/cron/weekly-recap',
    method: 'GET',
    icon: 'event_note',
    category: 'member',
    audienceDescription: 'Enrolled members with no recap this week',
    workflowKey: 'cron_weekly_recap',
  },
  {
    id: 'inactive-nudge',
    name: 'Inactive Nudge (All Members)',
    description: 'Sends re-engagement email to any member (enrolled or not) with 7+ days of inactivity who has reminders enabled.',
    schedule: '0 10 * * 1',
    scheduleLabel: 'Monday 10AM UTC',
    apiPath: '/api/cron/inactive-nudge',
    method: 'GET',
    icon: 'person_off',
    category: 'member',
    audienceDescription: 'All members with reminders on, inactive 7+ days',
    workflowKey: 'cron_inactive_nudge',
  },
  {
    id: 'inactivity-nudge',
    name: 'Inactivity Nudge (14-Day)',
    description: 'Sends re-engagement email to enrolled members with 14+ days of inactivity.',
    schedule: '0 10 * * 3',
    scheduleLabel: 'Wednesday 10AM UTC',
    apiPath: '/api/cron/inactivity-nudge',
    method: 'GET',
    icon: 'schedule_send',
    category: 'member',
    audienceDescription: 'Enrolled members inactive 14+ days',
    workflowKey: 'cron_inactivity_nudge',
  },
  {
    id: 'at-risk-alerts',
    name: 'At-Risk Alerts',
    description:
      'Weekly at-risk email: reads the CRITICAL AtRiskAlert rows the nightly check persisted (no re-scoring) and sends one batched alert per counselor; members with no counselor go to AT_RISK_DIGEST_EMAILS (fallback: admin inbox). Also runs the G5 member retention nudges (check-in / come-back / stuck, 7-day per-tier cooldown).',
    schedule: '7 13 * * 1',
    scheduleLabel: 'Monday 1PM UTC',
    apiPath: '/api/cron/at-risk-alerts',
    method: 'GET',
    icon: 'notification_important',
    category: 'admin',
    audienceDescription: 'Counselors — batched at-risk alerts (staff fallback for unassigned); members — retention nudges',
    workflowKey: 'cron_at_risk_alerts',
  },
  {
    id: 'applicant-followup',
    name: 'Applicant Follow-up Chases',
    description: 'Status emails to pending applicants at day 3, day 10 and day 20 (one per application per stage), plus a staff alert for the fresh 3–6 day queue.',
    schedule: '7 11 */3 * *',
    scheduleLabel: 'Every 3 days at 11:07 UTC',
    apiPath: '/api/cron/applicant-followup',
    method: 'GET',
    icon: 'follow_the_signs',
    category: 'member',
    audienceDescription: 'Applicants with pending status aged 3–6, 10–13 or 20–23 days',
    workflowKey: 'cron_applicant_followup',
  },
  {
    id: 'applicant-aging-digest',
    name: 'Aging Applications Digest',
    description: 'Weekly staff digest of pending and needs-info applications by age bucket, the ten waiting longest, and how many belong to members who already enrolled.',
    schedule: '37 14 * * 1',
    scheduleLabel: 'Monday 2:37PM UTC',
    apiPath: '/api/cron/applicant-aging-digest',
    method: 'GET',
    icon: 'pending_actions',
    category: 'admin',
    audienceDescription: 'Internal WorkforceAP admin team',
    workflowKey: 'cron_applicant_aging_digest',
  },
  {
    id: 'weekly-recap-email',
    name: 'Admin Weekly Recap',
    description: 'Weekly summary to WorkforceAP staff: new applicants, placements, at-risk students, pending applications.',
    schedule: '0 22 * * 5',
    scheduleLabel: 'Friday 10PM UTC (4PM CT)',
    apiPath: '/api/cron/weekly-recap-email',
    method: 'GET',
    icon: 'summarize',
    category: 'admin',
    audienceDescription: 'Internal WorkforceAP admin team',
    workflowKey: 'cron_weekly_recap_email',
  },
  {
    id: 'partner-outcome-digest',
    name: 'Partner Weekly Digest',
    description: 'Weekly referral outcome digest to each active partner — pipeline stage counts + weekly wins.',
    schedule: '0 13 * * 1',
    scheduleLabel: 'Monday 1PM UTC',
    apiPath: '/api/cron/partner-outcome-digest',
    method: 'GET',
    icon: 'handshake',
    category: 'partner',
    audienceDescription: 'Active partners with contact emails',
    workflowKey: 'cron_partner_digest',
  },
  {
    id: 'interview-reminders',
    name: 'Interview prep + debrief emails',
    description:
      'Sends a prep reminder ~24h before nextInterviewDate on the application tracker, and a short debrief prompt ~24h after.',
    schedule: '30 14 * * *',
    scheduleLabel: 'Daily 2:30 PM UTC',
    apiPath: '/api/cron/interview-reminders',
    method: 'GET',
    icon: 'event',
    category: 'member',
    audienceDescription: 'Members with interview dates on job applications',
    workflowKey: 'cron_interview_reminders',
  },
  {
    id: 'milestone-celebration',
    name: 'Milestone Celebration',
    description: 'Sends celebration emails for newly completed programs.',
    schedule: '0 11 * * *',
    scheduleLabel: 'Daily 11AM UTC',
    apiPath: '/api/cron/milestone-celebration',
    method: 'GET',
    icon: 'celebration',
    category: 'member',
    audienceDescription: 'Members who completed a program since yesterday',
    workflowKey: 'cron_milestone_celebration',
  },
  {
    id: 'smoke-test',
    name: 'Endpoint Smoke Test',
    description: 'HTTP checks on critical public paths to catch 500s/404s from bad deploys.',
    schedule: '0 * * * *',
    scheduleLabel: 'Hourly',
    apiPath: '/api/cron/smoke-test',
    method: 'GET',
    icon: 'wifi_tethering',
    category: 'admin',
    audienceDescription: 'Internal monitoring — no emails sent',
    workflowKey: 'cron_smoke_test',
  },
  {
    id: 'deploy-health',
    name: 'Vercel Deploy Health',
    description: 'Queries Vercel API to verify latest production deployment is READY, not ERROR.',
    schedule: '0 * * * *',
    scheduleLabel: 'Hourly',
    apiPath: '/api/cron/deploy-health',
    method: 'GET',
    icon: 'cloud_done',
    category: 'admin',
    audienceDescription: 'Internal monitoring — no emails sent',
    workflowKey: 'cron_deploy_health',
  },
  {
    id: 'verification',
    name: 'Cron Run Verification',
    description: 'Daily verification that all member-facing cron jobs actually executed in the last 24h.',
    schedule: '0 11 * * *',
    scheduleLabel: 'Daily 11AM UTC',
    apiPath: '/api/cron/verification',
    method: 'GET',
    icon: 'fact_check',
    category: 'admin',
    audienceDescription: 'Internal monitoring — no emails sent',
    workflowKey: 'cron_verification',
  },
  {
    id: 'coursera-training-sync',
    name: 'xAPI replay → course progress',
    description:
      'Replays pending xAPI rows into CourseProgress for any statements that arrived without a known userId/courseSlug.',
    schedule: '0 * * * *',
    scheduleLabel: 'Hourly at :00 UTC',
    apiPath: '/api/cron/coursera-training-sync',
    method: 'GET',
    icon: 'cloud_sync',
    category: 'admin',
    audienceDescription: 'Internal data sync (no outbound email)',
    workflowKey: 'cron_coursera_training_sync',
  },
  {
    id: 'coursera-sync',
    name: 'Coursera skillset progress sync',
    description:
      'Polls Coursera Enterprise per-learner skillset progress for every active member and upserts a snapshot row per (userId, skillsetId) into coursera_skillset_progress.',
    schedule: '0 */6 * * *',
    scheduleLabel: 'Every 6 hours',
    apiPath: '/api/cron/coursera-sync',
    method: 'GET',
    icon: 'school',
    category: 'admin',
    audienceDescription: 'Internal data sync (no outbound email)',
    workflowKey: 'cron_coursera_sync',
  },
  {
    id: 'coursera-b4b-sync',
    name: 'Coursera B4B enrollment sync',
    description:
      'Pulls Coursera For Business enrollment reports and writes/upserts course-level progress into CourseProgress + MemberProgramProgress. Staggered to :30 so it does not share the pooler with coursera-sync.',
    schedule: '30 */6 * * *',
    scheduleLabel: 'Every 6 hours at :30 UTC',
    apiPath: '/api/cron/coursera-b4b-sync',
    method: 'GET',
    icon: 'sync_alt',
    category: 'admin',
    audienceDescription: 'Internal data sync (no outbound email)',
    workflowKey: 'cron_coursera_b4b_sync',
  },
  {
    id: 'coursera-auto-heal',
    name: 'Coursera xAPI auto-heal',
    description:
      'Hourly unmatched xAPI reconciliation. B4B canonical seed + ignored replay run only when ignored events exist; quiet hours skip the B4B call.',
    schedule: '15 * * * *',
    scheduleLabel: 'Hourly at :15 UTC',
    apiPath: '/api/cron/coursera-auto-heal',
    method: 'GET',
    icon: 'healing',
    category: 'admin',
    audienceDescription: 'Internal data repair (no outbound member email)',
    workflowKey: 'cron_coursera_auto_heal',
  },
  {
    id: 'stale-training-check',
    name: 'Stale Coursera progress flag',
    description:
      'Flags members whose CourseEnrollment program has no fresh CourseProgress in 7 days (`User.staleTrainingDetectedAt`). Clears when progress resumes or program completes.',
    schedule: '30 12 * * *',
    scheduleLabel: 'Daily 12:30 UTC',
    apiPath: '/api/cron/stale-training-check',
    method: 'GET',
    icon: 'flag',
    category: 'admin',
    audienceDescription: 'Members with stale training signals for counselors',
    workflowKey: 'cron_stale_training_check',
  },
  {
    id: 'placement-survey',
    name: 'Post-Placement Survey',
    description:
      'Emails members with a placement from ~30 days ago who do not yet have a survey record, then creates PlacementSurvey.sentAt.',
    schedule: '0 14 * * *',
    scheduleLabel: 'Daily 2:00 PM UTC',
    apiPath: '/api/cron/placement-survey',
    method: 'GET',
    icon: 'rate_review',
    category: 'member',
    audienceDescription: 'Recently placed members (30-day window) with pending survey',
    workflowKey: 'cron_placement_survey',
  },
  {
    id: 'at-risk-check',
    name: 'At-Risk Member Check',
    description:
      'Nightly at-risk scoring for all active members. Calculates risk scores from engagement signals, training progress, and counselor contact recency; persists AtRiskAlert rows — the single risk source for both command centers, the at-risk dashboard and the weekly At-Risk Alerts email — and resolves stale alerts. Sends no email.',
    schedule: '11 6 * * *',
    scheduleLabel: 'Daily 6AM UTC',
    apiPath: '/api/cron/at-risk-check',
    method: 'GET',
    icon: 'crisis_alert',
    category: 'admin',
    audienceDescription: 'Internal — persisted risk for counselor/admin dashboards and the weekly alert',
    workflowKey: 'cron_at_risk_check',
  },
  {
    id: 'milestone-cascade-draft',
    name: 'Milestone Cascade Draft',
    description: 'Drafts milestone cascade emails for counselors to review before sending.',
    schedule: '0 * * * *',
    scheduleLabel: 'Hourly',
    apiPath: '/api/cron/milestone-cascade-draft',
    method: 'GET',
    icon: 'drafts',
    category: 'admin',
    audienceDescription: 'Internal — counselor draft queue',
    workflowKey: 'cron_milestone_cascade_draft',
  },
  {
    id: 'milestone-cascade-expire',
    name: 'Milestone Cascade Expire',
    description: 'Expires stale milestone cascade drafts that have not been reviewed.',
    schedule: '0 9 * * *',
    scheduleLabel: 'Daily 9AM UTC',
    apiPath: '/api/cron/milestone-cascade-expire',
    method: 'GET',
    icon: 'auto_delete',
    category: 'admin',
    audienceDescription: 'Internal — cleanup',
    workflowKey: 'cron_milestone_cascade_expire',
  },
  {
    id: 'data-cleanup',
    name: 'Data Cleanup',
    description: 'Runs periodic data cleanup and maintenance tasks.',
    schedule: '30 7 * * *',
    scheduleLabel: 'Daily 7:30 AM UTC',
    apiPath: '/api/cron/data-cleanup',
    method: 'GET',
    icon: 'cleaning_services',
    category: 'admin',
    audienceDescription: 'Internal — no emails sent',
    workflowKey: 'cron_data_cleanup',
  },
  {
    id: 'wioa-report',
    name: 'WIOA Report',
    description: 'Generates and sends monthly WIOA compliance report.',
    schedule: '0 14 1 * *',
    scheduleLabel: '1st of month 2PM UTC',
    apiPath: '/api/cron/wioa-report',
    method: 'GET',
    icon: 'summarize',
    category: 'admin',
    audienceDescription: 'Internal — WIOA compliance team',
    workflowKey: 'cron_wioa_report',
  },
  {
    id: 'course-accountability',
    name: 'Course Accountability',
    description: 'Checks course completion accountability and sends reminders.',
    schedule: '0 15 * * *',
    scheduleLabel: 'Daily 3PM UTC',
    apiPath: '/api/cron/course-accountability',
    method: 'GET',
    icon: 'account_balance',
    category: 'member',
    audienceDescription: 'Members with overdue course progress',
    workflowKey: 'cron_course_accountability',
  },
  {
    id: 'employer-pending-applicants',
    name: 'Employer Unreviewed-Applicants Nudge',
    description: 'Weekly nudge to employers with candidates stuck pending/reviewing 5+ days on their job posts, plus an admin digest for employers with a 10+ backlog.',
    schedule: '0 16 * * 2',
    scheduleLabel: 'Tuesday 4PM UTC',
    apiPath: '/api/cron/employer-pending-applicants',
    method: 'GET',
    icon: 'hourglass_top',
    category: 'employer',
    audienceDescription: 'Employers with stale applicants + internal admin digest',
    workflowKey: 'cron_employer_pending_applicants',
  },
  {
    id: 'job-expiry',
    name: 'Job Auto-Expiry',
    description: "Closes live job posts whose expiresAt has passed and notifies the affected employer once per run.",
    schedule: '45 7 * * *',
    scheduleLabel: 'Daily 7:45AM UTC',
    apiPath: '/api/cron/job-expiry',
    method: 'GET',
    // 'timer' is in the committed Material Symbols subset; 'event_busy' was
    // not, and the font-subset build guard fails on unsubsetted glyphs.
    icon: 'timer',
    category: 'employer',
    audienceDescription: 'Employers with jobs that just auto-expired',
    workflowKey: 'cron_job_expiry',
  },
  {
    id: 'onboarding-stalls',
    name: 'Onboarding Stalls Digest',
    description: 'Weekly staff digest of members stuck between applying and starting training: interviews requested but not completed, WIOA screening stuck in review, and members with no program or counselor 5-7+ days on.',
    schedule: '30 15 * * 2',
    scheduleLabel: 'Tuesday 3:30PM UTC',
    apiPath: '/api/cron/onboarding-stalls',
    method: 'GET',
    icon: 'pending_actions',
    category: 'admin',
    audienceDescription: 'Internal WorkforceAP admin team',
    workflowKey: 'cron_onboarding_stalls',
  },
];

export const CRON_CATEGORY_COLOR: Record<CronDef['category'], string> = {
  member: 'var(--color-accent)',
  admin: 'var(--color-blue, #2b7bb9)',
  partner: 'var(--color-gold)',
  employer: 'var(--color-green, #4a9b4f)',
};
